# Generated by Django 4.2.3 on 2023-07-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('confirmpassword', models.CharField(max_length=40)),
                ('status', models.CharField(default='U', max_length=10)),
            ],
        ),
    ]
