# Generated by Django 4.2.3 on 2023-07-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='thumbnail',
        ),
    ]
